#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.minimachine import muir, p3
from src.minimachine.user_image import build_bflt


def build_init_function() -> p3.Function:
    target = muir.Target(symbol="__mm_sys_user_milestone")
    return p3.Function(
        "__mm_user_init",
        [
            p3.Block(
                "entry",
                [
                    p3.Br(
                        muir.Width.I8,
                        muir.Cond.EQ,
                        muir.Imm(0),
                        muir.Imm(0),
                        target,
                        target,
                    )
                ],
            )
        ],
        set(),
    )


def c_bytes(data: bytes) -> str:
    rows = []
    for start in range(0, len(data), 12):
        chunk = data[start : start + 12]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join(rows)


def render_source(image: bytes) -> str:
    payload = c_bytes(image)
    return f"""// SPDX-License-Identifier: GPL-2.0-only
/*
 * Generated by scripts/build-minimachine-user-init.py.
 *
 * Boot-first userspace is a real Linux bFLT file whose text contains a
 * versioned MiniMachine P3 image.  The rootfs initcall writes the file through
 * Linux VFS so kernel_init() can discover /init through its normal exec path.
 */
#include <linux/err.h>
#include <linux/errno.h>
#include <linux/fcntl.h>
#include <linux/fs.h>
#include <linux/init.h>
#include <linux/printk.h>

static const unsigned char minimachine_user_init[] = {{
{payload}
}};

static int __init minimachine_seed_user_init(void)
{{
    struct file *file;
    loff_t pos = 0;
    ssize_t written;

    file = filp_open("/init", O_WRONLY | O_CREAT | O_TRUNC, 0755);
    if (IS_ERR(file))
        return PTR_ERR(file);

    written = kernel_write(file, minimachine_user_init,
                           sizeof(minimachine_user_init), &pos);
    fput(file);

    if (written < 0)
        return (int)written;
    if (written != sizeof(minimachine_user_init))
        return -EIO;

    pr_info("MiniMachine: seeded /init bFLT bytes=%zu\\n",
            sizeof(minimachine_user_init));
    return 0;
}}
rootfs_initcall(minimachine_seed_user_init);
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    image = build_bflt(build_init_function(), stack_size=64 * 1024)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_source(image))
    print(
        f"USER_INIT_C_READY path={args.output} bflt_bytes={len(image)}",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
